import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

SPEC = importlib.util.spec_from_file_location(
    "architecture_metrics", Path(__file__).resolve().parents[1] / "deucarian_architecture_metrics.py")
metrics = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(metrics)


class ArchitectureMetricsTests(unittest.TestCase):
    def scan(self, sources):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            (root / "package.json").write_text('{"name":"com.deucarian.test"}', encoding="utf-8")
            (root / "Runtime.asmdef").write_text('{"name":"Deucarian.Test"}', encoding="utf-8")
            for name, content in sources.items():
                path = root / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
            return metrics.scan_repository(root)

    def test_partial_types_aggregate_even_when_they_are_in_numbered_files(self):
        result = self.scan({
            "Controller.cs": "namespace Sample { partial class Controller { void A() {} } }",
            "Controller.Part01.cs": "namespace Sample { partial class Controller { void B() {} } }",
        })
        row = result["types"]["Deucarian.Test:Sample.Controller"]
        self.assertEqual(2, row["methods"])
        self.assertEqual(2, len(row["parts"]))

    def test_namespaces_nesting_and_generic_arity_do_not_collide(self):
        result = self.scan({
            "A.cs": "namespace A { class Item {} class Item<T> {} class Owner { class Item {} } }",
            "B.cs": "namespace B { class Item {} }",
        })
        self.assertEqual(5, len(result["types"]))
        self.assertIn("Deucarian.Test:A.Owner.Item", result["types"])
        self.assertIn("Deucarian.Test:A.Item`1", result["types"])

    def test_mutable_globals_include_readonly_collections_but_not_constants(self):
        result = self.scan({"A.cs": """
            class Globals {
                const int Answer = 42;
                static readonly string Name = "Dictionary static";
                static int First, Second;
                static readonly System.Collections.Generic.List<int> Values = new();
                static int Count { get; set; }
            }"""})
        self.assertEqual(4, next(iter(result["types"].values()))["mutableGlobals"])

    def test_comments_strings_and_local_names_do_not_create_global_fields(self):
        result = self.scan({"A.cs": """
            class Policy {
                // static int Fake;
                string Describe() { return "static int Fake; GUILayout File UnityWebRequest"; }
                void Run() { int local = 2; }
            }"""})
        row = next(iter(result["types"].values()))
        self.assertEqual(0, row["mutableGlobals"])
        self.assertEqual([], row["signals"])

    def test_responsibility_signals_are_advisory_not_new_gate_verdicts(self):
        result = self.scan({"A.cs": """
            class Presenter { void Draw() {
                GUILayout.Label("One"); File.ReadAllText("One"); UnityWebRequest.Get("One");
            } }"""})
        self.assertEqual(["presentation", "storage", "transport"], next(iter(result["types"].values()))["signals"])
        self.assertEqual([], metrics.compare(result, {}))

    def test_test_sources_and_generated_sources_do_not_count_as_production(self):
        result = self.scan({
            "Tests/Tests.asmdef": '{"name":"Deucarian.Tests","optionalUnityReferences":["TestAssemblies"]}',
            "Tests/Fixture.cs": "class Fixture { static int State; }",
            "Generated.g.cs": "// <auto-generated/>\nclass Generated { static int State; }",
            "Policy.cs": "class Policy {}",
        })
        self.assertEqual(["Deucarian.Test:Policy"], list(result["types"]))

    def test_existing_debt_is_allowed_but_growth_and_new_mutable_global_are_not(self):
        current = self.scan({"A.cs": "class Owner { static int Value; }"})
        key = next(iter(current["types"]))
        self.assertEqual("mutableGlobals", metrics.compare(current, {})[0]["metric"])
        baseline = {"types": {key: {"mutableGlobals": 1, "lines": 900}}}
        self.assertEqual([], metrics.compare(current, baseline))
        current["types"][key]["lines"] = 901
        self.assertEqual("lines", metrics.compare(current, baseline)[0]["metric"])

    def test_no_baseline_is_a_setup_error_not_an_implicit_approval(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            with self.assertRaisesRegex(ValueError, "baseline"):
                metrics.main(["--audit-root", str(root), "--baseline", str(root / "missing.json")])

    def test_explicit_exception_expires_when_the_package_version_changes(self):
        current = self.scan({"A.cs": "class Owner { static int Value; }"})
        current["version"] = "1.2.0"
        exception = {"assembly": "Deucarian.Test", "type": "Owner", "version": "1.2.0",
                     "limits": {"mutableGlobals": 1}, "reason": "One explicitly owned event bus."}
        self.assertEqual([], metrics.compare(current, {}, [exception]))
        current["version"] = "1.2.1"
        self.assertEqual(1, len(metrics.compare(current, {}, [exception])))
        exception["reason"] = ""
        with self.assertRaisesRegex(ValueError, "rationale"):
            metrics.compare(current, {}, [exception])

    def test_computed_static_properties_do_not_duplicate_their_backing_owner(self):
        result = self.scan({"A.cs": """
            class State {
                static int value;
                static int Computed { get { return value; } set { State.value = value; } }
                static object Factory { get { return new System.Collections.Generic.List<int>(); } }
            }"""})
        self.assertEqual(1, next(iter(result["types"].values()))["mutableGlobals"])

    def test_capture_and_check_round_trip_is_deterministic(self):
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            package = root / "Package"
            package.mkdir()
            (package / "package.json").write_text('{"name":"com.deucarian.test"}', encoding="utf-8")
            (package / "Runtime.asmdef").write_text('{"name":"Deucarian.Test"}', encoding="utf-8")
            (package / "Source.cs").write_text("class Owner { static int Value; }", encoding="utf-8")
            baseline = root / "baseline.json"
            arguments = ["--repository-root", str(package), "--baseline", str(baseline)]
            self.assertEqual(0, metrics.main(arguments + ["--write-baseline"]))
            before = baseline.read_bytes()
            self.assertEqual(0, metrics.main(arguments + ["--write-baseline"]))
            self.assertEqual(before, baseline.read_bytes())
            self.assertEqual(0, metrics.main(arguments))
            self.assertIn("com.deucarian.test", json.loads(before)["packages"])


if __name__ == "__main__":
    unittest.main()
