#!/usr/bin/env python3
"""Generate Deucarian organization governance audit artifacts.

The auditor is syntax-aware for C# when tree-sitter and tree_sitter_c_sharp
are installed. Authoritative mode fails instead of silently falling back.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

try:
    from tree_sitter import Language, Parser
    import tree_sitter_c_sharp

    CSHARP_LANGUAGE = Language(tree_sitter_c_sharp.language())
except Exception:  # pragma: no cover - exact import failure is reported at runtime.
    Parser = None
    CSHARP_LANGUAGE = None


SKIP_DIRS = {
    ".git",
    "Library",
    "PackageCache",
    "Temp",
    "Obj",
    "obj",
    "bin",
    ".vs",
    ".idea",
    "Logs",
    "UserSettings",
}
TEXT_EXTS = {".cs", ".json", ".asmdef", ".asmref", ".md", ".yml", ".yaml", ".ps1", ".sh", ".xml"}
GENERATED_MARKERS = ("<auto-generated", "auto-generated", "GeneratedCode")
DEBUG_METHODS = {
    "Log",
    "LogFormat",
    "LogWarning",
    "LogWarningFormat",
    "LogError",
    "LogErrorFormat",
    "LogException",
}
DEBUG_FORBIDDEN_SYMBOLS = [
    "UnityEngine.Debug.Log",
    "UnityEngine.Debug.LogFormat",
    "UnityEngine.Debug.LogWarning",
    "UnityEngine.Debug.LogWarningFormat",
    "UnityEngine.Debug.LogError",
    "UnityEngine.Debug.LogErrorFormat",
    "UnityEngine.Debug.LogException",
]
DESTROY_HELPER_NAMES = {
    "DestroyUnityObject",
    "DestroyUnityObjectSafely",
    "SafeDestroy",
    "DestroySafely",
    "DestroyObject",
}
CAPABILITIES = [
    ("logging", "com.deucarian.logging", "Category-based local package logging and Unity console forwarding."),
    ("editor-shell", "com.deucarian.editor", "Shared editor chrome, icons, resources, style tokens, editor-only UI Toolkit helpers."),
    ("api-http-client", "com.deucarian.api", "General HTTP/API request construction, transport, serialization, authentication, and cancellation."),
    ("session", "com.deucarian.session", "Authenticated session lifecycle, restore, refresh, logout, and persistence contracts."),
    ("object-loading", "com.deucarian.object-loading", "Object, scene, and AssetBundle loading lifecycle and handles."),
    ("repository-state", "com.deucarian.core-state", "Generic keyed repositories, selection state, and repository primitives."),
    ("ui-binding", "com.deucarian.ui-binding", "Collection-to-UI synchronization and presentation binding."),
    ("ui-flow", "com.deucarian.ui-flow", "UI routing, screens, channels, modals, guards, transitions, and back navigation."),
    ("world-selection", "com.deucarian.object-selection", "Keyed world-object selection, hover tracking, raycast adapters, and highlight hooks."),
    ("runtime-theming", "com.deucarian.theming", "Runtime palettes, theme assets, color roles, and UI theme adapters."),
    ("diagnostics", "com.deucarian.diagnostics", "Diagnostics providers, snapshots, JSON export, overlays, and aggregation."),
    ("package-management", "com.deucarian.package-installer", "Package discovery, install/update/remove, channels, registry composition, and ecosystem visualization."),
    ("registry-metadata", None, "Catalog, category hierarchy, dependency metadata, Integration metadata, Suite metadata, and governance metadata."),
    ("unity-object-lifetime", None, "Potential tiny shared UnityEngine.Object lifetime primitives if the dedicated audit justifies a Common package."),
]
OUTPUT_FILES = [
    "REUSE_AUDIT.md",
    "PACKAGE_CAPABILITY_MATRIX.md",
    "DEPENDENCY_GRAPH.md",
    "DUPLICATION_REPORT.json",
    "MIGRATION_PLAN.md",
    "capabilities.json",
    "dependency-rules.json",
    "DEBUG_API_AUDIT.json",
    "DEBUG_API_AUDIT.md",
    "UNITY_OBJECT_LIFETIME_AUDIT.json",
    "UNITY_OBJECT_LIFETIME_AUDIT.md",
    "DOCUMENTATION_DRIFT.json",
    "DOCUMENTATION_DRIFT.md",
    "DEPENDENCY_USAGE_AUDIT.json",
    "DEPENDENCY_USAGE_AUDIT.md",
    "EXTRACTION_DECISIONS.md",
]

parsed_repo_dependencies: dict[str, dict[str, str]] = {}
repo_asm_refs: dict[str, set[str]] = {}


@dataclass(order=True)
class SymbolContext:
    namespace: str = ""
    containing_type: str = ""
    symbol: str = ""
    kind: str = ""
    accessibility: str = ""
    effective_public: bool = False


@dataclass
class ParsedFile:
    repo: str
    package_id: str | None
    repo_root: Path
    path: Path
    relative_path: str
    scope: str
    assembly: str
    text: str
    tree: Any = None
    parse_error: str | None = None
    generated: bool = False
    aliases: dict[str, str] = field(default_factory=dict)
    using_unity_engine: bool = False
    symbols: list[dict[str, Any]] = field(default_factory=list)
    methods: list[dict[str, Any]] = field(default_factory=list)
    debug_invocations: list[dict[str, Any]] = field(default_factory=list)
    lifetime_occurrences: list[dict[str, Any]] = field(default_factory=list)

def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audit-root", type=Path, default=None, help="Root containing one checked-out repository per directory.")
    parser.add_argument("--output-root", type=Path, default=Path(__file__).resolve().parents[1], help="Directory where audit artifacts are written.")
    parser.add_argument("--organization", default="Deucarian", help="Canonical organization name for report labels.")
    parser.add_argument("--ref", default="develop", help="Git ref represented by the audit-root snapshots.")
    parser.add_argument("--authoritative", action="store_true", help="Fail if syntax-aware C# parsing is unavailable or any C# file cannot be parsed.")
    parser.add_argument("--format", choices=["all", "json", "markdown"], default="all", help="Artifact format subset to write.")
    parser.add_argument("--include-repository", action="append", default=[], help="Repository name to include; may be passed multiple times.")
    parser.add_argument("--exclude-repository", action="append", default=[], help="Repository name to exclude; may be passed multiple times.")
    parser.add_argument("--check", action="store_true", help="Regenerate into a temporary directory and fail if committed artifacts differ.")
    return parser


def repo_root_default(output_root: Path) -> Path:
    return output_root


def run(cmd: list[str], cwd: Path | None = None) -> tuple[str, str, int]:
    try:
        result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=60)
        return result.stdout.strip(), result.stderr.strip(), result.returncode
    except Exception as exc:
        return "", str(exc), 1


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return ""


def read_json(path: Path) -> Any:
    try:
        return json.loads(read_text(path))
    except Exception:
        return None


def write_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(sort_value(data), indent=2, ensure_ascii=True) + "\n", encoding="utf-8")


def sort_value(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: sort_value(value[key]) for key in sorted(value)}
    if isinstance(value, list):
        return [sort_value(item) for item in value]
    return value


def rel(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def iter_text_files(root: Path) -> Iterable[Path]:
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for filename in sorted(filenames):
            path = Path(dirpath) / filename
            if path.suffix in TEXT_EXTS:
                yield path


def scope_for(relative_path: str) -> str:
    first = relative_path.split("/", 1)[0]
    if first == "Runtime":
        return "Runtime production"
    if first == "Editor":
        return "Editor production"
    if first == "Tests":
        return "Test"
    if first.startswith("Samples"):
        return "Sample"
    if first in {"Tools", ".github"}:
        return "Build/CI"
    return "Other"


def assembly_for(relative_path: str, asmdefs: list[dict[str, Any]]) -> str:
    best = ""
    for asm in asmdefs:
        prefix = str(Path(asm["path"]).parent).replace("\\", "/")
        if prefix == ".":
            prefix = ""
        if not prefix or relative_path.startswith(prefix.rstrip("/") + "/"):
            if len(prefix) >= len(best):
                best = prefix
                assembly = asm.get("name", "")
    return locals().get("assembly", "")


def node_text(node: Any, source: bytes) -> str:
    return source[node.start_byte : node.end_byte].decode("utf-8", errors="replace")


def child_text(node: Any, field: str, source: bytes) -> str:
    child = node.child_by_field_name(field)
    return node_text(child, source) if child is not None else ""


def walk(node: Any) -> Iterable[Any]:
    yield node
    for child in node.children:
        yield from walk(child)


def direct_children(node: Any, types: set[str]) -> list[Any]:
    return [child for child in node.children if child.type in types]


def modifier_texts(node: Any, source: bytes) -> list[str]:
    return [node_text(child, source) for child in node.children if child.type == "modifier"]


def accessibility(node: Any, source: bytes, default: str = "private") -> str:
    modifiers = modifier_texts(node, source)
    for candidate in ("public", "protected internal", "protected", "internal", "private"):
        if candidate in " ".join(modifiers):
            return candidate
    return default


def is_generated_file(path: Path, text: str) -> bool:
    name = path.name.lower()
    return name.endswith(".g.cs") or name.endswith(".generated.cs") or name.endswith(".designer.cs") or any(marker.lower() in text[:1200].lower() for marker in GENERATED_MARKERS)


def is_production_scope(scope: str) -> bool:
    return scope in {"Runtime production", "Editor production"}


class CSharpSyntaxAnalyzer:
    declaration_types = {
        "class_declaration",
        "struct_declaration",
        "record_declaration",
        "record_struct_declaration",
        "interface_declaration",
        "enum_declaration",
        "delegate_declaration",
        "method_declaration",
        "constructor_declaration",
        "destructor_declaration",
        "local_function_statement",
        "property_declaration",
        "indexer_declaration",
        "event_declaration",
        "event_field_declaration",
        "operator_declaration",
        "conversion_operator_declaration",
    }
    type_declarations = {
        "class_declaration",
        "struct_declaration",
        "record_declaration",
        "record_struct_declaration",
        "interface_declaration",
        "enum_declaration",
        "delegate_declaration",
    }
    body_declarations = {
        "method_declaration",
        "constructor_declaration",
        "destructor_declaration",
        "local_function_statement",
        "operator_declaration",
        "conversion_operator_declaration",
        "property_declaration",
        "indexer_declaration",
    }

    def __init__(self, authoritative: bool = False):
        self.authoritative = authoritative
        self.available = Parser is not None and CSHARP_LANGUAGE is not None
        if self.available:
            self.parser = Parser()
            self.parser.language = CSHARP_LANGUAGE
        elif authoritative:
            raise RuntimeError("tree_sitter and tree_sitter_c_sharp are required for authoritative C# auditing.")

    def parse_file(self, parsed: ParsedFile) -> None:
        if parsed.generated:
            parsed.parse_error = "generated-code-excluded"
            return
        if not self.available:
            parsed.parse_error = "syntax-parser-unavailable"
            return

        source = parsed.text.encode("utf-8")
        parsed.tree = self.parser.parse(source)
        if parsed.tree.root_node.has_error:
            parsed.parse_error = "tree-sitter-parse-error"
            if self.authoritative:
                raise RuntimeError(f"C# parse error in {parsed.repo}/{parsed.relative_path}")

        parsed.aliases = self._find_aliases(parsed.tree.root_node, source)
        parsed.using_unity_engine = self._has_using_unity_engine(parsed.tree.root_node, source)
        self._collect_symbols(parsed, parsed.tree.root_node, source)
        self._collect_invocations(parsed, parsed.tree.root_node, source)

    def _find_aliases(self, root: Any, source: bytes) -> dict[str, str]:
        aliases: dict[str, str] = {}
        for node in walk(root):
            if node.type not in {"using_alias_directive", "using_directive"}:
                continue
            text = node_text(node, source)
            if "=" not in text:
                continue
            match = re.match(r"\s*using\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([^;]+);", text)
            if match:
                aliases[match.group(1)] = match.group(2).strip()
        return aliases

    def _has_using_unity_engine(self, root: Any, source: bytes) -> bool:
        for node in walk(root):
            if node.type == "using_directive" and node_text(node, source).strip() == "using UnityEngine;":
                return True
        return False

    def _collect_symbols(self, parsed: ParsedFile, root: Any, source: bytes) -> None:
        namespace_stack: list[str] = []
        type_stack: list[SymbolContext] = []

        def visit(node: Any) -> None:
            pushed_ns = False
            pushed_type = False
            if node.type in {"namespace_declaration", "file_scoped_namespace_declaration"}:
                name = child_text(node, "name", source)
                if name:
                    namespace_stack.append(name)
                    pushed_ns = True
            if node.type in self.declaration_types:
                kind = self._symbol_kind(node)
                name = self._symbol_name(node, source)
                access = accessibility(node, source, default="internal" if node.type in self.type_declarations else "private")
                containing_public = all(ctx.effective_public for ctx in type_stack) if type_stack else True
                type_public = access == "public" and containing_public
                member_public = access == "public" and containing_public and (not type_stack or type_stack[-1].effective_public)
                effective_public = type_public if node.type in self.type_declarations else member_public
                context = SymbolContext(
                    namespace=".".join(namespace_stack),
                    containing_type=".".join(ctx.symbol for ctx in type_stack),
                    symbol=name,
                    kind=kind,
                    accessibility=access,
                    effective_public=effective_public,
                )
                symbol_record = {
                    "repository": parsed.repo,
                    "packageId": parsed.package_id,
                    "assembly": parsed.assembly,
                    "scope": parsed.scope,
                    "namespace": context.namespace,
                    "containingType": context.containing_type,
                    "symbolKind": kind,
                    "symbol": name,
                    "fullSignature": self._signature(node, source),
                    "file": parsed.relative_path,
                    "line": node.start_point[0] + 1,
                    "xmlDocumentation": self._has_xml_doc(node, source),
                    "obsolete": self._has_attribute(node, source, "Obsolete"),
                    "accessibility": access,
                    "externallyPublic": effective_public and is_production_scope(parsed.scope),
                }
                parsed.symbols.append(symbol_record)
                if node.type in self.body_declarations:
                    method = self._method_record(parsed, node, source, context)
                    if method:
                        parsed.methods.append(method)
                if node.type in self.type_declarations:
                    type_stack.append(context)
                    pushed_type = True

            for child in node.children:
                visit(child)

            if pushed_type:
                type_stack.pop()
            if pushed_ns:
                namespace_stack.pop()

        visit(root)

    def _symbol_kind(self, node: Any) -> str:
        return {
            "class_declaration": "class",
            "struct_declaration": "struct",
            "record_declaration": "record",
            "record_struct_declaration": "record struct",
            "interface_declaration": "interface",
            "enum_declaration": "enum",
            "delegate_declaration": "delegate",
            "method_declaration": "method",
            "constructor_declaration": "constructor",
            "destructor_declaration": "destructor",
            "local_function_statement": "local function",
            "property_declaration": "property",
            "indexer_declaration": "indexer",
            "event_declaration": "event",
            "event_field_declaration": "event",
            "operator_declaration": "operator",
            "conversion_operator_declaration": "conversion operator",
        }.get(node.type, node.type)

    def _symbol_name(self, node: Any, source: bytes) -> str:
        if node.type == "indexer_declaration":
            return "this[]"
        if node.type == "operator_declaration":
            return "operator " + child_text(node, "operator", source)
        if node.type == "conversion_operator_declaration":
            return "conversion operator"
        name = child_text(node, "name", source)
        if name:
            return name
        for child in node.children:
            if child.type == "identifier":
                return node_text(child, source)
        return self._symbol_kind(node)

    def _signature(self, node: Any, source: bytes) -> str:
        text = node_text(node, source)
        for marker in ("{", "=>", ";"):
            idx = text.find(marker)
            if idx >= 0:
                text = text[:idx]
                break
        return " ".join(text.split())

    def _has_xml_doc(self, node: Any, source: bytes) -> bool:
        prefix = source[: node.start_byte].decode("utf-8", errors="replace")
        lines = prefix.splitlines()[-4:]
        return any(line.strip().startswith("///") for line in lines)

    def _has_attribute(self, node: Any, source: bytes, attr_name: str) -> bool:
        for child in node.children:
            if child.type == "attribute_list" and attr_name in node_text(child, source):
                return True
        return False

    def _method_record(self, parsed: ParsedFile, node: Any, source: bytes, context: SymbolContext) -> dict[str, Any] | None:
        body_nodes = [child for child in node.children if child.type in {"block", "arrow_expression_clause", "accessor_list"}]
        if not body_nodes:
            return None
        body_text = "\n".join(node_text(body, source) for body in body_nodes)
        if len(body_text.strip()) < 8:
            return None
        local_names = self._local_identifiers(node, source)
        normalized = normalize_body(body_text, local_names)
        if len(normalized) < 60:
            return None
        dependencies = sorted(set(re.findall(r"\b(?:UnityEngine|UnityEditor|System|Newtonsoft|Deucarian)\.[A-Za-z0-9_.]+", body_text)))
        return {
            "repository": parsed.repo,
            "packageId": parsed.package_id,
            "assembly": parsed.assembly,
            "scope": parsed.scope,
            "namespace": context.namespace,
            "containingType": context.containing_type,
            "symbol": context.symbol,
            "symbolKind": context.kind,
            "signature": self._signature(node, source),
            "file": parsed.relative_path,
            "line": node.start_point[0] + 1,
            "lineCount": max(1, node.end_point[0] - node.start_point[0] + 1),
            "dependenciesUsed": dependencies,
            "normalizedHash": hashlib.sha256(normalized.encode("utf-8")).hexdigest(),
            "normalizedStructural": normalized,
            "async": "async" in modifier_texts(node, source),
            "iterator": "yield" in body_text,
            "throws": "throw" in body_text,
            "editorApi": "UnityEditor" in body_text,
            "runtimeUnityApi": "UnityEngine" in body_text or "Object." in body_text,
        }

    def _local_identifiers(self, node: Any, source: bytes) -> set[str]:
        names: set[str] = set()
        for child in walk(node):
            if child.type == "parameter":
                name = child.child_by_field_name("name")
                if name is not None:
                    names.add(node_text(name, source))
            elif child.type == "variable_declarator":
                name = child.child_by_field_name("name")
                if name is not None:
                    names.add(node_text(name, source))
        return names

    def _collect_invocations(self, parsed: ParsedFile, root: Any, source: bytes) -> None:
        symbol_stack = self._symbol_ranges(parsed.symbols)
        for node in walk(root):
            if node.type != "invocation_expression":
                continue
            function = node.child_by_field_name("function")
            if function is None:
                continue
            invocation_name = self._invocation_name(function, source)
            containing_symbol = self._containing_symbol(symbol_stack, node.start_point[0] + 1)
            if self._is_debug_invocation(invocation_name, parsed):
                parsed.debug_invocations.append(self._debug_record(parsed, node, invocation_name, containing_symbol))
            lifetime_kind = self._lifetime_kind(invocation_name)
            if lifetime_kind:
                parsed.lifetime_occurrences.append(self._lifetime_record(parsed, node, invocation_name, containing_symbol, lifetime_kind))

    def _symbol_ranges(self, symbols: list[dict[str, Any]]) -> list[tuple[int, dict[str, Any]]]:
        return sorted((symbol["line"], symbol) for symbol in symbols)

    def _containing_symbol(self, ranges: list[tuple[int, dict[str, Any]]], line: int) -> str:
        current = ""
        for symbol_line, symbol in ranges:
            if symbol_line <= line:
                current = "::".join(part for part in [symbol.get("containingType"), symbol.get("symbol")] if part)
            else:
                break
        return current

    def _invocation_name(self, function: Any, source: bytes) -> str:
        return re.sub(r"\s+", "", node_text(function, source))

    def _is_debug_invocation(self, invocation_name: str, parsed: ParsedFile) -> bool:
        method = invocation_name.rsplit(".", 1)[-1]
        if method not in DEBUG_METHODS:
            return False
        prefix = invocation_name[: -(len(method) + 1)] if "." in invocation_name else ""
        if prefix in {"Debug", "UnityEngine.Debug", "global::UnityEngine.Debug"}:
            return parsed.using_unity_engine or prefix != "Debug"
        return parsed.aliases.get(prefix) in {"UnityEngine.Debug", "global::UnityEngine.Debug"}

    def _debug_record(self, parsed: ParsedFile, node: Any, invocation_name: str, containing_symbol: str) -> dict[str, Any]:
        logging_declared = bool((parsed_repo_dependencies.get(parsed.repo) or {}).get("com.deucarian.logging"))
        logging_asmdef = bool(repo_asm_refs.get(parsed.repo, set()) & {"Deucarian.Logging", "GUID:Deucarian.Logging"})
        classification = classify_scope(parsed.package_id, parsed.scope)
        disposition = "allowed" if classification in {"Test", "Bootstrap exception", "Logging package sink implementation"} else "migrate" if parsed.scope in {"Runtime production", "Editor production", "Sample"} else "review required"
        return {
            "repository": parsed.repo,
            "packageId": parsed.package_id,
            "file": parsed.relative_path,
            "line": node.start_point[0] + 1,
            "containingSymbol": containing_symbol,
            "scope": parsed.scope,
            "classification": classification,
            "invocation": invocation_name,
            "severity": "error" if disposition == "migrate" else "info",
            "loggingDeclared": logging_declared,
            "asmdefReferencesLogging": logging_asmdef,
            "initialDisposition": disposition,
        }

    def _lifetime_kind(self, invocation_name: str) -> str:
        method = invocation_name.rsplit(".", 1)[-1]
        if invocation_name in {"Object.Destroy", "UnityEngine.Object.Destroy", "global::UnityEngine.Object.Destroy"}:
            return "direct Unity API call"
        if invocation_name in {"Object.DestroyImmediate", "UnityEngine.Object.DestroyImmediate", "global::UnityEngine.Object.DestroyImmediate"}:
            return "direct Unity API call"
        if method in DESTROY_HELPER_NAMES:
            return "helper call site"
        return ""

    def _lifetime_record(self, parsed: ParsedFile, node: Any, invocation_name: str, containing_symbol: str, kind: str) -> dict[str, Any]:
        return {
            "repository": parsed.repo,
            "packageId": parsed.package_id,
            "file": parsed.relative_path,
            "line": node.start_point[0] + 1,
            "containingSymbol": containing_symbol,
            "scope": parsed.scope,
            "classification": classify_scope(parsed.package_id, parsed.scope),
            "occurrenceKind": kind,
            "invocation": invocation_name,
        }


def normalize_body(body_text: str, local_names: set[str]) -> str:
    text = re.sub(r"/\*.*?\*/", " ", body_text, flags=re.S)
    text = re.sub(r"//.*", " ", text)
    text = re.sub(r'@?"(?:""|\\.|[^"\\])*"', '"S"', text)
    text = re.sub(r"'(?:\\.|[^'\\])'", "'C'", text)
    text = re.sub(r"\b\d+(?:\.\d+)?\b", "0", text)
    for name in sorted(local_names, key=len, reverse=True):
        text = re.sub(rf"\b{re.escape(name)}\b", "local", text)
    return re.sub(r"\s+", "", text).lower()


def classify_scope(package_id: str | None, scope: str) -> str:
    if package_id == "com.deucarian.bootstrap":
        return "Bootstrap exception"
    if package_id == "com.deucarian.logging":
        return "Logging package sink implementation"
    if scope == "Test":
        return "Test"
    if scope == "Sample":
        return "Sample"
    if scope in {"Runtime production", "Editor production"}:
        return scope
    return "Unknown"


def collect_asmdefs(repo_root: Path) -> list[dict[str, Any]]:
    asmdefs = []
    for path in sorted(repo_root.rglob("*.asmdef")):
        relative_path = rel(path, repo_root)
        if any(part in SKIP_DIRS for part in relative_path.split("/")):
            continue
        data = read_json(path) or {}
        asmdefs.append(
            {
                "path": relative_path,
                "name": data.get("name", ""),
                "scope": scope_for(relative_path),
                "references": sorted(data.get("references", []) or []),
                "includePlatforms": sorted(data.get("includePlatforms", []) or []),
                "excludePlatforms": sorted(data.get("excludePlatforms", []) or []),
                "optionalUnityReferences": sorted(data.get("optionalUnityReferences", []) or []),
            }
        )
    return asmdefs


def collect_branch_info(repo_root: Path) -> dict[str, Any]:
    branch, _, _ = run(["git", "branch", "--show-current"], cwd=repo_root)
    status, _, _ = run(["git", "status", "--short"], cwd=repo_root)
    remote, _, _ = run(["git", "remote", "get-url", "origin"], cwd=repo_root)
    heads, _, _ = run(["git", "ls-remote", "--heads", "origin"], cwd=repo_root)
    return {
        "currentBranch": branch,
        "dirty": bool(status),
        "origin": remote,
        "hasDevelop": "refs/heads/develop" in heads,
        "hasMain": "refs/heads/main" in heads,
    }


def markdown_debug_examples(repo: dict[str, Any], repo_root: Path) -> list[dict[str, Any]]:
    hits = []
    for path in sorted(repo_root.rglob("*.md")):
        rel_path = rel(path, repo_root)
        if rel_path.upper().startswith("CHANGELOG"):
            continue
        in_fence = False
        for line_no, line in enumerate(read_text(path).splitlines(), start=1):
            if line.strip().startswith("```"):
                in_fence = not in_fence
                continue
            if in_fence and "Debug." in line:
                hits.append(
                    {
                        "repository": repo["name"],
                        "packageId": repo.get("packageId"),
                        "file": rel_path,
                        "line": line_no,
                        "scope": "Documentation example",
                        "classification": "Documentation example",
                        "invocation": line.strip(),
                        "initialDisposition": "review required",
                        "severity": "warning",
                        "loggingDeclared": bool(repo.get("dependencies", {}).get("com.deucarian.logging")),
                        "asmdefReferencesLogging": False,
                    }
                )
    return hits


def documentation_drift(repo: dict[str, Any], repo_root: Path, registry_package: dict[str, Any] | None) -> list[dict[str, Any]]:
    results = []
    readme_text = read_text(repo_root / "README.md")
    changelog_text = read_text(repo_root / "CHANGELOG.md")
    package_version = repo.get("packageVersion")
    readme_version = extract_readme_package_version(readme_text)
    latest_changelog = extract_changelog_version(changelog_text)
    if package_version and readme_version and package_version != readme_version:
        results.append({"kind": "package version drift", "repository": repo["name"], "packageId": repo.get("packageId"), "packageJsonVersion": package_version, "readmeVersion": readme_version})
    if package_version and latest_changelog and package_version != latest_changelog:
        results.append({"kind": "package version drift", "repository": repo["name"], "packageId": repo.get("packageId"), "packageJsonVersion": package_version, "changelogLatestVersion": latest_changelog})
    for dep, version in sorted((repo.get("dependencies") or {}).items()):
        pattern = rf"{re.escape(dep)}[^0-9]{{0,40}}(\d+\.\d+\.\d+)"
        for found in sorted(set(re.findall(pattern, readme_text, flags=re.I))):
            if found != version:
                results.append({"kind": "dependency version drift", "repository": repo["name"], "packageId": repo.get("packageId"), "dependency": dep, "packageJsonVersion": version, "readmeVersion": found})
    if registry_package:
        for url_key in ("stableUrl", "developmentUrl"):
            url = registry_package.get(url_key, "")
            branch = "main" if url_key == "stableUrl" else "develop"
            if url and not url.endswith("#" + branch):
                results.append({"kind": "branch URL drift", "repository": repo["name"], "packageId": repo.get("packageId"), "registryField": url_key, "url": url})
    for path in sorted(repo_root.rglob("*.md")):
        text = read_text(path)
        if re.search(r"\bBridge\b|\bbridge\b", text):
            results.append({"kind": "stale Bridge terminology", "repository": repo["name"], "packageId": repo.get("packageId"), "file": rel(path, repo_root)})
    return results


def extract_readme_package_version(text: str) -> str | None:
    patterns = [
        r"Current package version\s*[:|]\s*`?(\d+\.\d+\.\d+)`?",
        r"\|\s*Package version\s*\|\s*`?(\d+\.\d+\.\d+)`?\s*\|",
        r"\|\s*Version\s*\|\s*`?(\d+\.\d+\.\d+)`?\s*\|",
        r"!\[[^\]]*version[^\]]*\]\([^)]*/v?(\d+\.\d+\.\d+)[^)]*\)",
    ]
    for pattern in patterns:
        match = re.search(pattern, text, flags=re.I)
        if match:
            return match.group(1)
    return None


def extract_changelog_version(text: str) -> str | None:
    match = re.search(r"^##\s+\[?(\d+\.\d+\.\d+)\]?", text, flags=re.M)
    return match.group(1) if match else None


def dependency_usage(repo: dict[str, Any], parsed_files: list[ParsedFile], package_to_assemblies: dict[str, set[str]], registry_package: dict[str, Any] | None) -> list[dict[str, Any]]:
    usages = []
    repo_refs: set[str] = set()
    assembly_to_package = {
        assembly: package_id
        for package_id, assemblies in package_to_assemblies.items()
        for assembly in assemblies
    }
    for asm in repo.get("asmdefs", []):
        for reference in asm.get("references", []):
            clean = reference.replace("GUID:", "")
            repo_refs.add(clean)

    source_text = "\n".join(parsed.text for parsed in parsed_files)
    for dep, version in sorted((repo.get("dependencies") or {}).items()):
        if not dep.startswith("com.deucarian."):
            continue
        assemblies = package_to_assemblies.get(dep, set())
        referenced_by = []
        for asm in repo.get("asmdefs", []):
            for reference in asm.get("references", []):
                clean = reference.replace("GUID:", "")
                if clean in assemblies:
                    referenced_by.append(
                        {
                            "assembly": asm.get("name", ""),
                            "asmdef": asm.get("path", ""),
                            "scope": asm.get("scope", "Other"),
                            "reference": reference,
                        }
                    )
        asm_used = sorted({item["reference"].replace("GUID:", "") for item in referenced_by})
        namespace_hint = dep.replace("com.deucarian.", "Deucarian.").replace("-", ".")
        source_mentions = source_text.count(namespace_hint)
        scopes = {item["scope"] for item in referenced_by}
        if referenced_by and "Runtime production" in scopes:
            classification = "required and used"
        elif referenced_by and "Editor production" in scopes:
            classification = "editor-only use"
        elif referenced_by and scopes and scopes <= {"Test"}:
            classification = "test-only use"
        elif referenced_by and scopes and scopes <= {"Sample"}:
            classification = "sample-only use"
        elif referenced_by:
            classification = "review required"
        elif source_mentions:
            classification = "review required"
        else:
            classification = "apparently unused"
        usages.append({"repository": repo["name"], "packageId": repo.get("packageId"), "dependency": dep, "declaredVersion": version, "classification": classification, "referencedAssemblies": asm_used, "referencedBy": sorted(referenced_by, key=lambda item: (item["scope"], item["assembly"], item["reference"])), "sourceMentionCount": source_mentions})

    declared_deps = set((repo.get("dependencies") or {}).keys())
    for asm in repo.get("asmdefs", []):
        for reference in asm.get("references", []):
            clean = reference.replace("GUID:", "")
            owner = assembly_to_package.get(clean)
            if owner and owner != repo.get("packageId") and owner not in declared_deps:
                usages.append({"repository": repo["name"], "packageId": repo.get("packageId"), "assemblyReference": clean, "requiredPackage": owner, "referencingAssembly": asm.get("name", ""), "referencingAsmdef": asm.get("path", ""), "scope": asm.get("scope", "Other"), "classification": "missing package dependency"})
    return usages


def clone_groups(methods: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[dict[str, Any]]]:
    by_hash: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for method in methods:
        by_hash[method["normalizedHash"]].append(method)

    exact = []
    structural = []
    for hash_value, occurrences in by_hash.items():
        repos = sorted(set(item["repository"] for item in occurrences))
        if len(occurrences) > 1 and len(repos) > 1:
            group = build_clone_group("normalized structural clone", hash_value, occurrences)
            structural.append(group)
            if len(set(item["signature"] for item in occurrences)) == 1:
                exact.append({**group, "category": "exact AST clone"})

    same_symbol: list[dict[str, Any]] = []
    by_symbol: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for method in methods:
        if any(token in method["symbol"].lower() for token in ["destroy", "dispose", "cleanup", "log", "validate", "guard", "json", "wait"]):
            by_symbol[method["symbol"].lower()].append(method)
    for symbol, occurrences in by_symbol.items():
        repos = sorted(set(item["repository"] for item in occurrences))
        if len(repos) >= 2:
            same_symbol.append(build_clone_group("same-symbol semantic candidate", symbol, occurrences))

    exact.sort(key=lambda item: (-item["repositoryCount"], -item["estimatedDuplicatedLines"], item["groupKey"]))
    structural.sort(key=lambda item: (-item["repositoryCount"], -item["estimatedDuplicatedLines"], item["groupKey"]))
    same_symbol.sort(key=lambda item: (-item["repositoryCount"], item["groupKey"]))
    return exact, structural, same_symbol


def build_clone_group(category: str, key: str, occurrences: list[dict[str, Any]]) -> dict[str, Any]:
    repos = sorted(set(item["repository"] for item in occurrences))
    line_counts = [item["lineCount"] for item in occurrences]
    scopes = sorted(set(item["scope"] for item in occurrences))
    deps = sorted(set(dep for item in occurrences for dep in item.get("dependenciesUsed", [])))
    confidence = "needs design review"
    reasons_to_extract = []
    reasons_not = []
    if len(repos) >= 3 and any(scope in {"Runtime production", "Editor production"} for scope in scopes):
        confidence = "medium"
        reasons_to_extract.append("Same parsed implementation appears in at least three repositories.")
    else:
        reasons_not.append("Does not cross the production extraction threshold without manual semantic review.")
    if any(item.get("editorApi") for item in occurrences) and any(item["scope"] == "Runtime production" for item in occurrences):
        reasons_not.append("Mixed editor/runtime API semantics require scope-specific review.")
        confidence = "low"
    return {
        "category": category,
        "groupKey": key,
        "repositoryCount": len(repos),
        "repositories": repos,
        "scopes": scopes,
        "estimatedDuplicatedLines": max(0, sum(line_counts) - max(line_counts)),
        "dependenciesUsed": deps,
        "proposedOwner": propose_owner(occurrences),
        "extractionConfidence": confidence,
        "reasonsToExtract": reasons_to_extract,
        "reasonsNotToExtract": reasons_not,
        "occurrences": [{k: v for k, v in item.items() if k != "normalizedStructural"} for item in sorted(occurrences, key=lambda i: (i["repository"], i["file"], i["line"]))],
    }


def propose_owner(occurrences: list[dict[str, Any]]) -> str:
    if any(item.get("editorApi") or item["scope"] == "Editor production" for item in occurrences):
        return "com.deucarian.editor"
    if any("logging" in item["symbol"].lower() or "log" in item["symbol"].lower() for item in occurrences):
        return "com.deucarian.logging"
    if any("destroy" in item["symbol"].lower() for item in occurrences):
        return "pending unity-object-lifetime decision"
    return "needs capability-owner review"


def helper_definition_records(parsed_files: list[ParsedFile]) -> list[dict[str, Any]]:
    records = []
    for parsed in parsed_files:
        for method in parsed.methods:
            if method["symbol"] not in DESTROY_HELPER_NAMES:
                continue
            body = method.get("normalizedStructural", "")
            text = parsed.text
            line = method["line"]
            snippet = "\n".join(text.splitlines()[line - 1 : line + method["lineCount"]])
            records.append(
                {
                    "repository": method["repository"],
                    "packageId": method["packageId"],
                    "file": method["file"],
                    "line": line,
                    "symbol": method["symbol"],
                    "scope": method["scope"],
                    "occurrenceKind": "helper definition",
                    "semantics": {
                        "handlesNullOrFakeNull": "==null" in body or "!=null" in body or "?." in snippet,
                        "usesPlayModeCheck": "application.isplaying" in body,
                        "usesDestroy": "object.destroy(" in body or ".destroy(" in body,
                        "usesDestroyImmediate": "destroyimmediate" in body,
                        "clearsReferences": "=null" in body,
                        "handlesCollections": "foreach" in body or "ienumerable" in body or ".clear(" in body,
                        "catchesExceptions": "catch" in body,
                    },
                    "assemblyPlatform": parsed.assembly,
                }
            )
    return records


def load_registry(output_root: Path) -> dict[str, Any]:
    data = read_json(output_root / "packages.json") or {}
    return {pkg.get("id"): pkg for pkg in data.get("packages", []) if pkg.get("id")}


def build_report(args: argparse.Namespace) -> dict[str, Any]:
    output_root = args.output_root.resolve()
    audit_root = (args.audit_root or repo_root_default(output_root)).resolve()
    registry = load_registry(output_root)
    include = {name.lower() for name in args.include_repository}
    exclude = {name.lower() for name in args.exclude_repository}

    analyzer = CSharpSyntaxAnalyzer(authoritative=args.authoritative)
    repositories: list[dict[str, Any]] = []
    parsed_files: list[ParsedFile] = []
    parse_failures: list[dict[str, Any]] = []

    for repo_root in sorted([p for p in audit_root.iterdir() if p.is_dir()], key=lambda p: p.name.lower()):
        if include and repo_root.name.lower() not in include:
            continue
        if repo_root.name.lower() in exclude:
            continue
        package_json = read_json(repo_root / "package.json") or {}
        asmdefs = collect_asmdefs(repo_root)
        repo = {
            "name": repo_root.name,
            "canonicalId": f"{args.organization}/{repo_root.name}",
            "packageId": package_json.get("name"),
            "packageVersion": package_json.get("version"),
            "unity": package_json.get("unity"),
            "displayName": package_json.get("displayName"),
            "branches": collect_branch_info(repo_root),
            "dependencies": package_json.get("dependencies", {}) or {},
            "asmdefs": asmdefs,
            "registryDependencies": (registry.get(package_json.get("name")) or {}).get("dependencies") if package_json.get("name") else None,
            "registryGroupId": (registry.get(package_json.get("name")) or {}).get("groupId") if package_json.get("name") else None,
            "ciWorkflows": sorted(rel(p, repo_root) for p in (repo_root / ".github" / "workflows").glob("*.y*ml")) if (repo_root / ".github" / "workflows").exists() else [],
            "validationScripts": sorted(rel(p, repo_root) for p in repo_root.glob("Tools/**/*") if p.is_file() and "validat" in p.name.lower()),
            "samples": sorted(rel(p, repo_root) for p in repo_root.glob("Samples~/**/*") if p.is_file())[:80],
        }
        repositories.append(repo)

        for path in sorted(repo_root.rglob("*.cs")):
            relative_path = rel(path, repo_root)
            if any(part in SKIP_DIRS for part in relative_path.split("/")):
                continue
            text = read_text(path)
            parsed = ParsedFile(
                repo=repo_root.name,
                package_id=repo.get("packageId"),
                repo_root=repo_root,
                path=path,
                relative_path=relative_path,
                scope=scope_for(relative_path),
                assembly=assembly_for(relative_path, asmdefs),
                text=text,
                generated=is_generated_file(path, text),
            )
            analyzer.parse_file(parsed)
            if parsed.parse_error and parsed.parse_error != "generated-code-excluded":
                parse_failures.append({"repository": parsed.repo, "file": parsed.relative_path, "error": parsed.parse_error})
            parsed_files.append(parsed)

    global parsed_repo_dependencies, repo_asm_refs
    parsed_repo_dependencies = {repo["name"]: repo.get("dependencies", {}) for repo in repositories}
    repo_asm_refs = {
        repo["name"]: set(ref for asm in repo.get("asmdefs", []) for ref in asm.get("references", []))
        for repo in repositories
    }
    # Recollect invocations now dependency globals are available for records.
    for parsed in parsed_files:
        parsed.debug_invocations.clear()
        parsed.lifetime_occurrences.clear()
        if parsed.tree is not None:
            analyzer._collect_invocations(parsed, parsed.tree.root_node, parsed.text.encode("utf-8"))

    if args.authoritative and parse_failures:
        raise RuntimeError(f"Authoritative parse failed for {len(parse_failures)} C# files.")

    all_symbols = [symbol for parsed in parsed_files for symbol in parsed.symbols]
    production_api = [symbol for symbol in all_symbols if symbol.get("externallyPublic")]
    public_missing_xml = [symbol for symbol in production_api if not symbol.get("xmlDocumentation")]
    runtime_api = [symbol for symbol in production_api if symbol["scope"] == "Runtime production"]
    editor_api = [symbol for symbol in production_api if symbol["scope"] == "Editor production"]
    test_public = [symbol for symbol in all_symbols if symbol["scope"] == "Test" and symbol["accessibility"] == "public"]
    sample_public = [symbol for symbol in all_symbols if symbol["scope"] == "Sample" and symbol["accessibility"] == "public"]
    internal_private = [symbol for symbol in all_symbols if is_production_scope(symbol["scope"]) and not symbol.get("externallyPublic")]
    methods = [method for parsed in parsed_files for method in parsed.methods]
    exact_clones, structural_clones, semantic_candidates = clone_groups(methods)

    package_to_assemblies = defaultdict(set)
    for repo in repositories:
        if repo.get("packageId"):
            for asm in repo.get("asmdefs", []):
                if asm.get("name"):
                    package_to_assemblies[repo["packageId"]].add(asm["name"])

    debug_records = [record for parsed in parsed_files for record in parsed.debug_invocations]
    for repo in repositories:
        repo_root = audit_root / repo["name"]
        debug_records.extend(markdown_debug_examples(repo, repo_root))
    debug_records.sort(key=lambda item: (item["repository"], item["file"], item["line"], item.get("invocation", "")))

    lifetime_records = [record for parsed in parsed_files for record in parsed.lifetime_occurrences]
    lifetime_records.extend(helper_definition_records(parsed_files))
    lifetime_records.sort(key=lambda item: (item["repository"], item["file"], item["line"], item.get("occurrenceKind", "")))

    documentation_records = []
    dependency_usage_records = []
    for repo in repositories:
        repo_root = audit_root / repo["name"]
        registry_package = registry.get(repo.get("packageId"))
        documentation_records.extend(documentation_drift(repo, repo_root, registry_package))
        dependency_usage_records.extend(dependency_usage(repo, [p for p in parsed_files if p.repo == repo["name"]], package_to_assemblies, registry_package))
    documentation_records.sort(key=lambda item: (item["repository"], item["kind"], item.get("file", ""), item.get("dependency", "")))
    dependency_usage_records.sort(key=lambda item: (item["repository"], item.get("dependency", item.get("assemblyReference", ""))))

    edges = []
    versions_by_pkg = {repo["packageId"]: repo["packageVersion"] for repo in repositories if repo.get("packageId")}
    version_drifts = []
    registry_drifts = []
    for repo in repositories:
        for dep, version in sorted((repo.get("dependencies") or {}).items()):
            if dep.startswith("com.deucarian."):
                edges.append({"from": repo.get("packageId"), "to": dep, "version": version, "fromRepo": repo["name"], "toRepo": next((r["name"] for r in repositories if r.get("packageId") == dep), None)})
                owner_version = versions_by_pkg.get(dep)
                if owner_version and version != owner_version:
                    version_drifts.append({"repo": repo["name"], "packageId": repo.get("packageId"), "dependency": dep, "declaredVersion": version, "ownerDevelopVersion": owner_version})
        if repo.get("registryDependencies") is not None:
            pkg_deps = sorted(dep for dep in (repo.get("dependencies") or {}) if dep.startswith("com.deucarian."))
            reg_deps = sorted(repo.get("registryDependencies") or [])
            if pkg_deps != reg_deps:
                registry_drifts.append({"repo": repo["name"], "packageId": repo.get("packageId"), "packageJsonDependencies": pkg_deps, "registryDependencies": reg_deps})

    capability_matrix = []
    for cap_id, owner, desc in CAPABILITIES:
        owner_repo = next((repo["name"] for repo in repositories if repo.get("packageId") == owner), None)
        consumers = sorted(set(edge["from"] for edge in edges if edge["to"] == owner))
        capability_matrix.append({"id": cap_id, "ownerPackageId": owner, "ownerRepository": owner_repo or ("Package-Registry" if cap_id == "registry-metadata" else None), "description": desc, "currentConsumers": consumers})

    lifetime_conclusion = classify_lifetime_conclusion(lifetime_records)
    extraction_decisions = reviewed_extraction_decisions(exact_clones, structural_clones, semantic_candidates, lifetime_conclusion)

    return {
        "metadata": {
            "schemaVersion": 2,
            "organization": args.organization,
            "ref": args.ref,
            "parser": "tree-sitter-c-sharp" if analyzer.available else "unavailable",
            "authoritative": args.authoritative,
            "generatedAtUtc": "not-recorded-deterministic-output",
        },
        "repositories": repositories,
        "parseFailures": parse_failures,
        "publicApi": {
            "runtimeProductionCount": len(runtime_api),
            "editorProductionCount": len(editor_api),
            "testsPublicCount": len(test_public),
            "samplesPublicCount": len(sample_public),
            "internalPrivateProductionCount": len(internal_private),
            "runtimeProduction": sort_symbols(runtime_api),
            "editorProduction": sort_symbols(editor_api),
            "tests": sort_symbols(test_public),
            "samples": sort_symbols(sample_public),
            "internalPrivate": sort_symbols(internal_private),
            "symbols": sort_symbols(production_api),
            "missingXmlDocumentation": sort_symbols(public_missing_xml),
        },
        "duplication": {
            "methodCountAnalyzed": len(methods),
            "exactAstCloneGroups": exact_clones,
            "normalizedStructuralCloneGroups": structural_clones,
            "sameSymbolSemanticCandidates": semantic_candidates,
            "similarLookingButSemanticallyDifferent": [],
        },
        "debugApi": {
            "invocations": debug_records,
            "summary": summarize_by(debug_records, "initialDisposition"),
        },
        "unityObjectLifetime": {
            "occurrences": lifetime_records,
            "summary": summarize_by(lifetime_records, "occurrenceKind"),
            "conclusion": lifetime_conclusion,
        },
        "documentationDrift": {
            "findings": documentation_records,
            "summary": summarize_by(documentation_records, "kind"),
        },
        "dependencyUsage": {
            "findings": dependency_usage_records,
            "summary": summarize_by(dependency_usage_records, "classification"),
        },
        "dependencyGraph": {"edges": sorted(edges, key=lambda e: (e.get("from") or "", e.get("to") or "")), "cycles": detect_cycles(edges)},
        "drift": {"dependencyVersionDrift": sorted(version_drifts, key=lambda x: (x["repo"], x["dependency"])), "registryDependencyDrift": sorted(registry_drifts, key=lambda x: x["repo"])},
        "capabilityMatrix": capability_matrix,
        "extractionDecisions": extraction_decisions,
    }


def summarize_by(records: list[dict[str, Any]], key: str) -> dict[str, int]:
    counts: dict[str, int] = defaultdict(int)
    for record in records:
        counts[str(record.get(key, "(none)"))] += 1
    return dict(sorted(counts.items()))


def sort_symbols(symbols: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(symbols, key=lambda symbol: (symbol["repository"], symbol["file"], symbol["line"], symbol["symbol"]))


def detect_cycles(edges: list[dict[str, Any]]) -> list[list[str]]:
    graph: dict[str, list[str]] = defaultdict(list)
    for edge in edges:
        if edge.get("from") and edge.get("to"):
            graph[edge["from"]].append(edge["to"])
    cycles: list[list[str]] = []
    stack: list[str] = []
    seen: set[str] = set()

    def visit(node: str, visiting: set[str]) -> None:
        if node in visiting:
            cycle = stack[stack.index(node) :] + [node]
            if cycle not in cycles:
                cycles.append(cycle)
            return
        if node in seen:
            return
        visiting.add(node)
        stack.append(node)
        for nxt in sorted(graph.get(node, [])):
            visit(nxt, visiting)
        stack.pop()
        visiting.remove(node)
        seen.add(node)

    for node in sorted(graph):
        visit(node, set())
    return cycles


def classify_lifetime_conclusion(records: list[dict[str, Any]]) -> dict[str, Any]:
    helper_defs = [r for r in records if r.get("occurrenceKind") == "helper definition"]
    runtime = [r for r in records if r.get("scope") == "Runtime production"]
    editor = [r for r in records if r.get("scope") == "Editor production"]
    tests = [r for r in records if r.get("scope") == "Test"]
    if runtime and editor:
        decision = "multiple scope-specific owners required"
    elif runtime and len({r["repository"] for r in runtime}) >= 3:
        decision = "runtime Common package justified"
    elif editor:
        decision = "Editor-owned helper justified"
    elif tests and len({r["repository"] for r in tests}) >= 3:
        decision = "Testing-owned helper justified"
    else:
        decision = "no extraction justified"
    return {
        "decision": decision,
        "helperDefinitionCount": len(helper_defs),
        "runtimeRepositoryCount": len({r["repository"] for r in runtime}),
        "editorRepositoryCount": len({r["repository"] for r in editor}),
        "testRepositoryCount": len({r["repository"] for r in tests}),
        "note": "No package is created by this audit wave; this conclusion directs the next design review.",
    }


def reviewed_extraction_decisions(exact: list[dict[str, Any]], structural: list[dict[str, Any]], semantic: list[dict[str, Any]], lifetime: dict[str, Any]) -> list[dict[str, Any]]:
    decisions = []
    for group in structural[:50]:
        if group["extractionConfidence"] == "medium":
            decision = "Needs design review"
        else:
            decision = "Keep local"
        decisions.append({"candidate": group["groupKey"], "category": group["category"], "repositories": group["repositories"], "decision": decision, "reasoning": "; ".join(group["reasonsNotToExtract"] or group["reasonsToExtract"] or ["Manual semantic review required."])})
    for group in semantic[:50]:
        decisions.append({"candidate": group["groupKey"], "category": group["category"], "repositories": group["repositories"], "decision": "Needs design review", "reasoning": "Same symbol names are not enough to extract; review semantics and owner capability."})
    decisions.append({"candidate": "unity-object-lifetime", "category": "dedicated audit", "repositories": [], "decision": lifetime["decision"], "reasoning": lifetime["note"]})
    return sorted(decisions, key=lambda item: (item["category"], item["candidate"]))


def md_table(headers: list[str], rows: Iterable[Iterable[Any]]) -> str:
    out = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    for row in rows:
        out.append("| " + " | ".join(str(cell).replace("\n", " ").replace("|", "\\|") for cell in row) + " |")
    return "\n".join(out)


def write_artifacts(report: dict[str, Any], output_root: Path, formats: str = "all") -> None:
    output_root.mkdir(parents=True, exist_ok=True)
    json_enabled = formats in {"all", "json"}
    md_enabled = formats in {"all", "markdown"}

    if json_enabled:
        write_json(output_root / "DUPLICATION_REPORT.json", report)
        write_json(output_root / "DEBUG_API_AUDIT.json", report["debugApi"])
        write_json(output_root / "UNITY_OBJECT_LIFETIME_AUDIT.json", report["unityObjectLifetime"])
        write_json(output_root / "DOCUMENTATION_DRIFT.json", report["documentationDrift"])
        write_json(output_root / "DEPENDENCY_USAGE_AUDIT.json", report["dependencyUsage"])
        write_json(output_root / "capabilities.json", capabilities_json(report))
        write_json(output_root / "dependency-rules.json", dependency_rules_json(report))

    if not md_enabled:
        return

    write_reuse_audit(report, output_root / "REUSE_AUDIT.md")
    write_capability_matrix(report, output_root / "PACKAGE_CAPABILITY_MATRIX.md")
    write_dependency_graph(report, output_root / "DEPENDENCY_GRAPH.md")
    write_migration_plan(report, output_root / "MIGRATION_PLAN.md")
    write_debug_md(report, output_root / "DEBUG_API_AUDIT.md")
    write_lifetime_md(report, output_root / "UNITY_OBJECT_LIFETIME_AUDIT.md")
    write_doc_drift_md(report, output_root / "DOCUMENTATION_DRIFT.md")
    write_dependency_usage_md(report, output_root / "DEPENDENCY_USAGE_AUDIT.md")
    write_extraction_decisions_md(report, output_root / "EXTRACTION_DECISIONS.md")


def capabilities_json(report: dict[str, Any]) -> dict[str, Any]:
    caps = []
    for cap in report["capabilityMatrix"]:
        item = {"id": cap["id"], "ownerPackageId": cap.get("ownerPackageId"), "description": cap["description"]}
        if cap["id"] == "logging":
            item["forbiddenSymbolsOutsideOwner"] = DEBUG_FORBIDDEN_SYMBOLS
            item["exceptions"] = [
                {"packageId": "com.deucarian.bootstrap", "reason": "First-time self-contained bootstrap."},
                {"packageId": "com.deucarian.logging", "reason": "Owns Unity console forwarding and sink validation."},
            ]
        if cap["id"] == "unity-object-lifetime":
            item["status"] = report["unityObjectLifetime"]["conclusion"]["decision"]
        caps.append(item)
    return {"schemaVersion": 2, "capabilities": caps}


def dependency_rules_json(report: dict[str, Any]) -> dict[str, Any]:
    return {
        "schemaVersion": 2,
        "layers": [
            {"id": "common", "packages": ["com.deucarian.common"], "status": "not-created"},
            {"id": "foundation", "packages": ["com.deucarian.editor", "com.deucarian.logging", "com.deucarian.core-state"]},
            {"id": "runtime-capabilities", "packages": ["com.deucarian.api", "com.deucarian.session", "com.deucarian.object-loading", "com.deucarian.object-selection", "com.deucarian.ui-binding", "com.deucarian.ui-flow", "com.deucarian.theming", "com.deucarian.diagnostics"]},
            {"id": "integrations", "packages": ["com.deucarian.session.api-integration", "com.deucarian.object-loading.api-integration", "com.deucarian.object-selection.core-state-integration", "com.deucarian.ui-binding.core-state-integration"]},
            {"id": "suites", "packages": ["com.deucarian.selection-suite"]},
            {"id": "catalog-composition", "packages": ["com.deucarian.package-installer"]},
        ],
        "exceptions": [
            {"packageId": "com.deucarian.bootstrap", "reason": "Self-contained first-time setup package outside normal dependency graph."},
            {"packageId": "com.deucarian.logging", "dependency": "com.deucarian.editor", "status": "review-required", "reason": "Review Logging -> Editor before allowing Editor to use Logging."},
        ],
        "rules": [
            "No cyclic package dependencies.",
            "Runtime assemblies must not reference UnityEditor.",
            "Common, if created, cannot depend on Logging or Editor.",
            "Logging cannot depend on Diagnostics or telemetry.",
            "Integration packages depend only on their targets plus Common/Logging when actually used.",
            "Package Registry dependencies must match package.json direct Deucarian dependencies.",
            "Assembly references must match package dependencies.",
        ],
    }


def write_reuse_audit(report: dict[str, Any], path: Path) -> None:
    repos = report["repositories"]
    rows = [
        [
            repo["name"],
            repo.get("packageId") or "(none)",
            repo.get("packageVersion") or "(none)",
            repo.get("unity") or "(none)",
            "yes" if repo["branches"]["hasDevelop"] else "no",
            "clean" if not repo["branches"]["dirty"] else "dirty",
            ", ".join(repo["dependencies"].keys()) or "(none)",
            str(len(repo["asmdefs"])),
            str(sum(1 for s in report["publicApi"]["symbols"] if s["repository"] == repo["name"])),
        ]
        for repo in repos
    ]
    path.write_text(
        f"""# Deucarian Reuse Audit

Schema version: {report['metadata']['schemaVersion']}

This is the hardened organization-wide audit snapshot for `{report['metadata']['organization']}` at `{report['metadata']['ref']}`. It uses `{report['metadata']['parser']}` for C# parsing and does not migrate package source.

## Weaknesses Fixed From The Original Audit

- Replaced regex/braces C# discovery with syntax-aware Tree-sitter parsing.
- Public API counts now include only externally public Runtime and Editor production symbols.
- Debug usage counts now come from invocation expressions instead of prose/text matches.
- Unity object lifetime findings separate helper definitions, helper calls, and direct Unity API calls.
- Documentation version drift detection no longer treats every semantic version in README prose as the package version.
- Audit paths are repository-relative/canonical; no machine-specific audit-root paths are written.

## Inventory

{md_table(['Repository', 'Package ID', 'Version', 'Unity', 'Develop', 'Audit Clone', 'package.json dependencies', 'Asmdefs', 'Production public API'], rows)}

## Corrected Counts

- Repositories: {len(repos)}
- Parsed methods/bodies analyzed: {report['duplication']['methodCountAnalyzed']}
- Exact AST clone groups: {len(report['duplication']['exactAstCloneGroups'])}
- Normalized structural clone groups: {len(report['duplication']['normalizedStructuralCloneGroups'])}
- Same-symbol semantic candidates: {len(report['duplication']['sameSymbolSemanticCandidates'])}
- Runtime public API symbols: {report['publicApi']['runtimeProductionCount']}
- Editor public API symbols: {report['publicApi']['editorProductionCount']}
- Public API symbols missing XML documentation: {len(report['publicApi']['missingXmlDocumentation'])}
- Debug invocation records: {len(report['debugApi']['invocations'])}
- Unity object lifetime records: {len(report['unityObjectLifetime']['occurrences'])}
- Documentation drift findings: {len(report['documentationDrift']['findings'])}
- Dependency usage findings: {len(report['dependencyUsage']['findings'])}
- Dependency cycles: {len(report['dependencyGraph']['cycles'])}

## Extraction Position

No Common, Testing, Build Tools, or package dependency migration is performed by this audit. `EXTRACTION_DECISIONS.md` records reviewed dispositions for candidates produced by the hardened analyzer.
""",
        encoding="utf-8",
    )


def write_capability_matrix(report: dict[str, Any], path: Path) -> None:
    rows = [
        [cap["id"], cap.get("ownerPackageId") or "(pending)", cap.get("ownerRepository") or "(pending)", ", ".join(cap.get("currentConsumers") or []) or "(none)"]
        for cap in report["capabilityMatrix"]
    ]
    path.write_text(
        f"""# Deucarian Package Capability Matrix

Schema version: 2

{md_table(['Capability', 'Owner package', 'Owner repository', 'Current package.json consumers'], rows)}

## Notes

- `unity-object-lifetime` remains governed by the dedicated lifetime audit conclusion: {report['unityObjectLifetime']['conclusion']['decision']}.
- `Logging -> Editor` remains a review-required dependency exception.
- Capability ownership does not automatically justify adding dependencies; consumers must use the capability.
""",
        encoding="utf-8",
    )


def write_dependency_graph(report: dict[str, Any], path: Path) -> None:
    rows = [[e.get("from"), e.get("to"), e.get("version"), e.get("fromRepo"), e.get("toRepo") or "(not in inventory)"] for e in report["dependencyGraph"]["edges"]]
    cycles = report["dependencyGraph"]["cycles"]
    cycle_text = "None detected." if not cycles else "\n".join("- " + " -> ".join(c) for c in cycles)
    path.write_text(
        f"""# Deucarian Dependency Graph

Schema version: 2

## Direct Deucarian Package Dependencies

{md_table(['From package', 'To package', 'Declared version', 'From repo', 'To repo'], rows)}

## Cycle Report

{cycle_text}

## Version Drift

- Dependency version drift entries: {len(report['drift']['dependencyVersionDrift'])}
- Registry dependency drift entries: {len(report['drift']['registryDependencyDrift'])}
""",
        encoding="utf-8",
    )


def write_migration_plan(report: dict[str, Any], path: Path) -> None:
    path.write_text(
        f"""# Deucarian Migration Plan

Schema version: 2

This plan remains audit/governance-only. No production source, package dependencies, package versions, package READMEs, or main branches are changed.

## Next Safe Steps

1. Review `EXTRACTION_DECISIONS.md` before extracting any clone candidate.
2. Address Debug API findings from `DEBUG_API_AUDIT.md`; production/sample findings marked `migrate` should move to `com.deucarian.logging` in a later source wave.
3. Review `UNITY_OBJECT_LIFETIME_AUDIT.md`; conclusion: {report['unityObjectLifetime']['conclusion']['decision']}.
4. Resolve `DOCUMENTATION_DRIFT.md` findings before dependency migrations.
5. Use `DEPENDENCY_USAGE_AUDIT.md` to decide which dependencies are required, editor-only, sample-only, apparently unused, or review required.
6. Add architecture validation using `capabilities.json` and `dependency-rules.json`.

## Still Not Done

- No Common package.
- No Testing package.
- No Build Tools repository.
- No package dependency changes.
- No source migrations.
""",
        encoding="utf-8",
    )


def write_debug_md(report: dict[str, Any], path: Path) -> None:
    records = report["debugApi"]["invocations"]
    rows = [[r["repository"], r["file"], r["line"], r["scope"], r["invocation"], r["initialDisposition"]] for r in records[:200]]
    path.write_text(
        f"""# Debug API Audit

Schema version: 1

Counts actual C# invocation expressions plus fenced Markdown examples. Comments, strings, CHANGELOG mentions, and test method names are excluded from production-code counts.

Summary: {json.dumps(report['debugApi']['summary'], sort_keys=True)}

{md_table(['Repository', 'File', 'Line', 'Scope', 'Invocation', 'Disposition'], rows)}
""",
        encoding="utf-8",
    )


def write_lifetime_md(report: dict[str, Any], path: Path) -> None:
    records = report["unityObjectLifetime"]["occurrences"]
    rows = [[r["repository"], r["file"], r["line"], r["scope"], r.get("occurrenceKind"), r.get("invocation", r.get("symbol", ""))] for r in records[:240]]
    path.write_text(
        f"""# Unity Object Lifetime Audit

Schema version: 1

Conclusion: **{report['unityObjectLifetime']['conclusion']['decision']}**

Summary: {json.dumps(report['unityObjectLifetime']['summary'], sort_keys=True)}

{md_table(['Repository', 'File', 'Line', 'Scope', 'Kind', 'Symbol/Invocation'], rows)}
""",
        encoding="utf-8",
    )


def write_doc_drift_md(report: dict[str, Any], path: Path) -> None:
    rows = [[r["repository"], r["kind"], r.get("file", ""), r.get("dependency", ""), r.get("packageJsonVersion", r.get("url", "")), r.get("readmeVersion", r.get("changelogLatestVersion", ""))] for r in report["documentationDrift"]["findings"][:200]]
    path.write_text(
        f"""# Documentation Drift Audit

Schema version: 1

Summary: {json.dumps(report['documentationDrift']['summary'], sort_keys=True)}

{md_table(['Repository', 'Kind', 'File', 'Dependency', 'Expected/Value', 'Found'], rows)}
""",
        encoding="utf-8",
    )


def write_dependency_usage_md(report: dict[str, Any], path: Path) -> None:
    rows = []
    for record in report["dependencyUsage"]["findings"][:240]:
        evidence = "; ".join(
            f"{item.get('scope', 'Other')}: {item.get('assembly', '')} -> {item.get('reference', '')}"
            for item in record.get("referencedBy", [])
        )
        if record.get("classification") == "missing package dependency":
            evidence = f"{record.get('scope', 'Other')}: {record.get('referencingAssembly', '')} -> {record.get('assemblyReference', '')}"
        rows.append([record["repository"], record.get("dependency", record.get("assemblyReference", "")), record["classification"], evidence, ", ".join(record.get("referencedAssemblies", [])), record.get("sourceMentionCount", "")])
    path.write_text(
        f"""# Dependency Usage Audit

Schema version: 1

Summary: {json.dumps(report['dependencyUsage']['summary'], sort_keys=True)}

Findings marked `apparently unused` are review prompts, not removal recommendations.

{md_table(['Repository', 'Dependency/Reference', 'Classification', 'Evidence', 'Referenced assemblies', 'Source mentions'], rows)}
""",
        encoding="utf-8",
    )


def write_extraction_decisions_md(report: dict[str, Any], path: Path) -> None:
    rows = [[d["candidate"], d["category"], ", ".join(d.get("repositories", [])), d["decision"], d["reasoning"]] for d in report["extractionDecisions"]]
    path.write_text(
        f"""# Extraction Decisions

Schema version: 1

These decisions are manual-review defaults produced after hardening the analyzer. They deliberately avoid extraction from occurrence count alone.

{md_table(['Candidate', 'Category', 'Repositories', 'Decision', 'Reasoning'], rows)}
""",
        encoding="utf-8",
    )


def check_artifacts(args: argparse.Namespace, report: dict[str, Any]) -> int:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_root = Path(tmp)
        write_artifacts(report, tmp_root, args.format)
        stale = []
        for filename in OUTPUT_FILES:
            expected = tmp_root / filename
            actual = args.output_root / filename
            if not expected.exists() and not actual.exists():
                continue
            if not expected.exists() or not actual.exists() or expected.read_bytes() != actual.read_bytes():
                stale.append(filename)
        if stale:
            print("Audit artifacts are stale:", ", ".join(stale), file=sys.stderr)
            return 1
    print("Audit artifacts are up to date.")
    return 0


def main() -> int:
    parser = build_arg_parser()
    args = parser.parse_args()
    args.output_root = args.output_root.resolve()
    if args.audit_root is None:
        args.audit_root = repo_root_default(args.output_root)
    args.audit_root = args.audit_root.resolve()
    report = build_report(args)
    if args.check:
        return check_artifacts(args, report)
    write_artifacts(report, args.output_root, args.format)
    print(json.dumps({
        "repositories": len(report["repositories"]),
        "methodsAnalyzed": report["duplication"]["methodCountAnalyzed"],
        "runtimePublicApi": report["publicApi"]["runtimeProductionCount"],
        "editorPublicApi": report["publicApi"]["editorProductionCount"],
        "debugInvocations": len(report["debugApi"]["invocations"]),
        "lifetimeOccurrences": len(report["unityObjectLifetime"]["occurrences"]),
        "documentationDrift": len(report["documentationDrift"]["findings"]),
        "dependencyUsageFindings": len(report["dependencyUsage"]["findings"]),
        "cycles": len(report["dependencyGraph"]["cycles"]),
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
